import moment from 'moment'
import VuetifyColorsPallete from '~/shared/VuetifyColorsPallete'
import { emptyLine } from '../../reports'
import {
  generateDataFromColumnsAndData,
  generateHeadersFromColumns,
} from '../helpers'
import {
  ldrAllColumns,
  // ldrCallsColumns,
  ldr_PPC_CallsColumns,
  ldr_FB_CallsColumns,
  ldr_SEO_CallsColumns,
  // ldrChatsColumns,
  ldr_PPC_ChatsColumns,
  ldr_FB_ChatsColumns,
  ldr_SEO_ChatsColumns,
  ldr_FB_FormsColumns,
  ldr_PPC_FormsColumns,
  ldr_SEO_FormsColumns,
} from './columns'

const generateLeadDetailsReport = (
  computedReport: any,
  user: any,
  LDRReport: any
) => {
  const locationNames = LDRReport.locations
    .map((location: any) => {
      return location?.location?.name
    })
    .filter((name: string) => name)

  const totalReportDays =
    moment(computedReport.value.date_end).diff(
      moment(computedReport.value.date_start),
      'days'
    ) + 1
  return {
    type: 'lead-details-report',
    name: `LDR, ${locationNames.join(',')}, ${
      computedReport.value.client.name
    }, ${computedReport.value.date_start}, ${
      computedReport.value.date_end
    }, Generated by ${user.fullname}`,
    sheets: [
      {
        title: 'Lead Summary',
        headings: {
          rowStyle: {
            fontSize: '12px',
            fontWeight: 'bold',
            color: '#f6f6f6',
            bgColor: '#727272',
            width: '30px',
            textAlign: 'left',
          },
          data: [],
        },
        content: [
          {
            data: [
              {
                value: `Client Name: `,
                styles: {
                  width: '400px',
                },
              },
              {
                value: `${computedReport.value.client.name}`,
                styles: {
                  width: '400px',
                },
              },
            ],
          },
          {
            data: [
              {
                value: `Date: `,
                styles: {},
              },
              {
                value: `${computedReport.value.date_start} - ${computedReport.value.date_end} (${totalReportDays} days)`,
                styles: {},
              },
            ],
          },
          {
            data: [
              {
                value: `Locations:`,
                styles: {
                  width: '400px',
                },
              },
            ],
          },

          ...LDRReport.locations.map((location: any) => {
            return {
              data: [
                {
                  value: `${location?.location?.name || ''}`,
                  styles: {
                    width: '400px',
                  },
                },
              ],
            }
          }),

          emptyLine,
          emptyLine,
          {
            data: [
              { value: 'Lead Type' },
              { value: 'Count' },
              { value: 'Unique' },
            ],
          },
          {
            data: [
              { value: 'Calls' },
              { value: computedReport.value.summary.calls.total },
              { value: computedReport.value.summary.calls.unique },
            ],
          },
          {
            data: [
              { value: 'Chats' },
              { value: computedReport.value.summary.chats.total },
              { value: computedReport.value.summary.chats.unique },
            ],
          },
          {
            data: [
              { value: 'Forms' },
              { value: computedReport.value.summary.emails.total },
              { value: computedReport.value.summary.emails.unique },
            ],
          },
          {
            data: [
              { value: 'Facebook' },
              { value: computedReport.value.summary.facebook_leads.total },
              { value: computedReport.value.summary.facebook_leads.unique },
            ],
          },
          {
            data: [
              { value: 'Total' },
              {
                value:
                  computedReport.value.summary.calls.total +
                  computedReport.value.summary.chats.total +
                  computedReport.value.summary.emails.total +
                  computedReport.value.summary.facebook_leads.total,
              },
              {
                value:
                  computedReport.value.summary.calls.unique +
                  computedReport.value.summary.chats.unique +
                  computedReport.value.summary.emails.unique +
                  computedReport.value.summary.facebook_leads.unique,
              },
            ],
          },
          emptyLine,
          {
            data: [
              { value: 'CPL' },
              {
                value: `$${new Number(
                  (computedReport.value.lead_analytics.aggregate.total_spend / 
                    (computedReport.value.summary.calls.unique +
                    computedReport.value.summary.chats.unique +
                    computedReport.value.summary.emails.unique +
                    computedReport.value.summary.facebook_leads.unique)) || 0
                ).toFixed(2)}`,
              },
            ],
          },
          {
            data: [
              { value: 'Conversions' },
              {
                value: `${
                  computedReport.value.lead_analytics.aggregate.conversions ||
                  ''
                }`,
              },
            ],
          },
          {
            data: [
              { value: 'Total Spend Adwords' },
              {
                value: `$${new Number(
                  computedReport.value.lead_analytics.adwords.total_spend || 0
                ).toFixed(2)}`,
              },
            ],
          },
          {
            data: [
              { value: 'Total Spend Facebook' },
              {
                value: `$${new Number(
                  computedReport.value.lead_analytics.facebook.total_spend || 0
                ).toFixed(2)}`,
              },
            ],
          },
          {
            data: [
              { value: 'Total Spend' },
              {
                value: `$${new Number(
                  computedReport.value.lead_analytics.aggregate.total_spend || 0
                ).toFixed(2)}`,
              },
            ],
          },
        ],
      },
      {
        title: 'For AM USE ONLY',
        headings: {
          rowStyle: {
            fontSize: '12px',
            fontWeight: 'bold',
            color: '#f6f6f6',
            bgColor: '#727272',
            width: '30px',
            textAlign: 'left',
          },
          data: [],
        },
        content: [
          {
            data: [
              { value: 'FOR AM USE ONLY',
              styles: {
                width: ''
              },
            },
            ],
          },
          emptyLine,
          {
            data: [
              { value: 'Lead Source',
              styles: {
                        width: '',
                        fontWeight: 'bold'
                      }, 
                    },
              { value: 'ADWORDS',
              styles: {
                width: '',
              },
            },
              { value: '' },
              { value: '' },
              { value: '' },
              { value: '' },

            // Lead Source - FACEBOOK

              { value: 'Lead Source',
              styles: {
                        width: '',
                        fontWeight: 'bold'
                      }, 
                    },
              { value: 'FACEBOOK',
              styles: {
                width: '',
              },
            },
              { value: '' },
              { value: '' },
              { value: '' },
            ],
          },
          {
            data: [
              { value: 'Lead Type',
               styles: {
                fontWeight: 'bold',
                bgColor: '#D9EAD3',
              },
            },
              { value: 'Count',
              styles: {
                fontWeight: 'bold',
                bgColor: '#D9EAD3',
              },
            },
              { value: 'Unique',
              styles: {
                fontWeight: 'bold',
                bgColor: '#D9EAD3',
              },
            },
              { value: 'Percentage of Unique Leads',
              styles: {
                fontWeight: 'bold',
                bgColor: '#D9EAD3',
              },
            },
              { value: 'Conversion % (CLicks/Unique Leads)',
              styles: {
                fontWeight: 'bold',
                bgColor: '#D9EAD3',
              },
            },
            { value: '' },

            // Lead Source - FACEBOOK

            { value: 'Lead Type',
               styles: {
                fontWeight: 'bold',
                bgColor: '#C9DAF8',
              },
            },
              { value: 'Count',
              styles: {
                fontWeight: 'bold',
                bgColor: '#C9DAF8',
              },
            },
              { value: 'Unique',
              styles: {
                fontWeight: 'bold',
                bgColor: '#C9DAF8',
              },
            },
              { value: 'Percentage of Unique Leads',
              styles: {
                fontWeight: 'bold',
                bgColor: '#C9DAF8',
              },
            },
              { value: 'Conversion % (impressions/Unique Leads)',
              styles: {
                fontWeight: 'bold',
                bgColor: '#C9DAF8',
              },
            },
            ],
          },
          {
            data: [
              { value: 'Calls',
              styles: {
                fontWeight: 'bold',
                bgColor: '#D9EAD3',
              }, 
            },
              { value: computedReport.value.details.am.adwords.calls.total || 0 },
              { value: computedReport.value.details.am.adwords.calls.unique || 0 },
              { value: ( computedReport.value.details.am.adwords.calls.unique / 
                ( computedReport.value.details.am.adwords.calls.unique + 
                  computedReport.value.details.am.adwords.chats.unique +
                  computedReport.value.details.am.adwords.forms.unique ) ) == Infinity  ? 0 + '%' :  
                  `${new Number(( computedReport.value.details.am.adwords.calls.unique / 
                ( computedReport.value.details.am.adwords.calls.unique + 
                  computedReport.value.details.am.adwords.chats.unique +
                  computedReport.value.details.am.adwords.forms.unique ) ) || 0 * 100).toFixed(2)}%` },
              { value: ( computedReport.value.details.am.adwords.clicks / 
                ( computedReport.value.details.am.adwords.calls.unique) ) == Infinity  ? 0 + '%' :  
                `${new Number(( computedReport.value.details.am.adwords.clicks / 
                ( computedReport.value.details.am.adwords.calls.unique) ) || 0).toFixed(2)}%` },
              { value: ' ' },

              // Lead Source - FACEBOOK

              { value: 'Calls',
              styles: {
                fontWeight: 'bold',
                bgColor: '#C9DAF8',
              }, 
            },
            { value: computedReport.value.details.am.facebook.calls.total || 0 },
            { value: computedReport.value.details.am.facebook.calls.unique || 0 },
            { value: ( computedReport.value.details.am.facebook.calls.unique / 
              ( computedReport.value.details.am.facebook.calls.unique + 
                computedReport.value.details.am.facebook.chats.unique +
                computedReport.value.details.am.facebook.forms.unique ) ) == Infinity  ? 0 + '%' :  
                `${new Number(( computedReport.value.details.am.facebook.calls.unique / 
              ( computedReport.value.details.am.facebook.calls.unique + 
                computedReport.value.details.am.facebook.chats.unique +
                computedReport.value.details.am.facebook.forms.unique ) ) || 0 * 100).toFixed(2) || 0 }%` },
            { value: ( computedReport.value.details.am.facebook.impressions / 
              ( computedReport.value.details.am.facebook.calls.unique) ) == Infinity  ? 0 + '%' :  
              `${new Number(( computedReport.value.details.am.facebook.impressions / 
              ( computedReport.value.details.am.facebook.calls.unique) ) || 0).toFixed(2)}%` },
            ],
          },
          {
            data: [
              { value: 'Chats',
              styles: {
                fontWeight: 'bold',
                bgColor: '#D9EAD3',
              },
             },
             { value: computedReport.value.details.am.adwords.chats.total || 0 },
             { value: computedReport.value.details.am.adwords.chats.unique || 0 },
             { value: ( computedReport.value.details.am.adwords.chats.unique / 
              ( computedReport.value.details.am.adwords.calls.unique + 
                computedReport.value.details.am.adwords.chats.unique +
                computedReport.value.details.am.adwords.forms.unique ) ) == Infinity  ? 0 + '%' :  
                `${new Number(( computedReport.value.details.am.adwords.chats.unique / 
              ( computedReport.value.details.am.adwords.calls.unique + 
                computedReport.value.details.am.adwords.chats.unique +
                computedReport.value.details.am.adwords.forms.unique ) ) || 0 * 100).toFixed(2)}%` },
             { value: ( computedReport.value.details.am.adwords.clicks / 
              ( computedReport.value.details.am.adwords.chats.unique) ) == Infinity  ? 0 + '%' :  
              `${new Number(( computedReport.value.details.am.adwords.clicks / 
              ( computedReport.value.details.am.adwords.chats.unique) ) || 0).toFixed(2)}%` },
            { value: ' ' },

              // Lead Source - FACEBOOK

              { value: 'Chats',
              styles: {
                fontWeight: 'bold',
                bgColor: '#C9DAF8',
              },
             },
             { value: computedReport.value.details.am.facebook.chats.total || 0 },
             { value: computedReport.value.details.am.facebook.chats.unique || 0 },
             { value: ( computedReport.value.details.am.facebook.chats.unique / 
              ( computedReport.value.details.am.facebook.calls.unique + 
                computedReport.value.details.am.facebook.chats.unique +
                computedReport.value.details.am.facebook.forms.unique ) ) == Infinity  ? 0 + '%' :  
                `${new Number(( computedReport.value.details.am.facebook.chats.unique / 
              ( computedReport.value.details.am.facebook.calls.unique + 
                computedReport.value.details.am.facebook.chats.unique +
                computedReport.value.details.am.facebook.forms.unique ) ) || 0 * 100).toFixed(2)}%` },
             { value: ( computedReport.value.details.am.facebook.impressions / 
              ( computedReport.value.details.am.facebook.chats.unique) ) == Infinity  ? 0 + '%' : 
              `${new Number(( computedReport.value.details.am.facebook.impressions / 
              ( computedReport.value.details.am.facebook.chats.unique) ) || 0).toFixed(2)}%` },
            ],
          },
          {
            data: [
              { value: 'Forms',
              styles: {
                fontWeight: 'bold',
                bgColor: '#D9EAD3',
              },
            },
             { value: computedReport.value.details.am.adwords.forms.total || 0 },
             { value: computedReport.value.details.am.adwords.forms.unique || 0 },
             { value: ( computedReport.value.details.am.adwords.forms.unique / 
              ( computedReport.value.details.am.adwords.calls.unique + 
                computedReport.value.details.am.adwords.chats.unique +
                computedReport.value.details.am.adwords.forms.unique ) ) == Infinity  ? 0 + '%' : 
                `${new Number(( computedReport.value.details.am.adwords.forms.unique / 
              ( computedReport.value.details.am.adwords.calls.unique + 
                computedReport.value.details.am.adwords.chats.unique +
                computedReport.value.details.am.adwords.forms.unique ) ) || 0 * 100).toFixed(2)}%` },
             { value: ( computedReport.value.details.am.adwords.clicks / 
              ( computedReport.value.details.am.adwords.forms.unique) ) == Infinity  ? 0 + '%' : 
              `${new Number(( computedReport.value.details.am.adwords.clicks / 
                  ( computedReport.value.details.am.adwords.forms.unique) ) || 0).toFixed(2)}%` },
              { value: ' ' },


              // Lead Source - FACEBOOK

              { value: 'Forms',
              styles: {
                fontWeight: 'bold',
                bgColor: '#C9DAF8',
              },
            },
             { value: computedReport.value.details.am.facebook.forms.total || 0 },
             { value: computedReport.value.details.am.facebook.forms.unique || 0 },
             { value: ( computedReport.value.details.am.facebook.forms.unique / 
              ( computedReport.value.details.am.facebook.calls.unique + 
                computedReport.value.details.am.facebook.chats.unique +
                computedReport.value.details.am.facebook.forms.unique ) ) == Infinity  ? 0 + '%' : 
                `${new Number(( computedReport.value.details.am.facebook.forms.unique / 
              ( computedReport.value.details.am.facebook.calls.unique + 
                computedReport.value.details.am.facebook.chats.unique +
                computedReport.value.details.am.facebook.forms.unique ) ) || 0 * 100).toFixed(2)}%` },
             { value: ( computedReport.value.details.am.facebook.impressions / 
              ( computedReport.value.details.am.facebook.forms.unique) ) == Infinity  ? 0 + '%' : 
              `${new Number(( computedReport.value.details.am.facebook.impressions / 
              ( computedReport.value.details.am.facebook.forms.unique) ) || 0).toFixed(2)}%` },
            ],
          },
          {
            data: [
              { value: 'Total # of Leads',
              styles: {
                fontWeight: 'bold',
                bgColor: '#D9EAD3',
              },
            },
              { value: (computedReport.value.details.am.adwords.calls.total + 
                computedReport.value.details.am.adwords.chats.total + 
                computedReport.value.details.am.adwords.forms.total) || 0 },
              { value: (computedReport.value.details.am.adwords.calls.unique + 
                computedReport.value.details.am.adwords.chats.unique + 
                computedReport.value.details.am.adwords.forms.unique) || 0 },
              { value: ' '},
              { value: ' '},
              { value: ' '},


              // Lead Source - FACEBOOK

              { value: 'Total # of Leads',
              styles: {
                fontWeight: 'bold',
                bgColor: '#C9DAF8',
              },
            },
            { value: (computedReport.value.details.am.facebook.calls.total + 
              computedReport.value.details.am.facebook.chats.total + 
              computedReport.value.details.am.facebook.forms.total) || 0 },
            { value: (computedReport.value.details.am.facebook.calls.unique + 
              computedReport.value.details.am.facebook.chats.unique + 
              computedReport.value.details.am.facebook.forms.unique ) || 0 },
              { value: ' '},
              { value: ' '},
            ],
          },
          emptyLine,
          {
            data: [
              { value: 'Total AdWords Spend',
              styles: {
                fontWeight: 'bold',
                bgColor: '#D9EAD3',
              },
            },
              { value:  `$${new Number(
                computedReport.value.lead_analytics.adwords.total_spend).toFixed(2) || 0}`},
              { value: ' '},
              { value: ' '},
              { value: ' '},
              { value: ' '},


              // Lead Source - FACEBOOK

              { value: 'Total FB Spend',
              styles: {
                fontWeight: 'bold',
                bgColor: '#C9DAF8',
              },
            },
              { value: `$${new Number(
                computedReport.value.lead_analytics.facebook.total_spend).toFixed(2) || 0}` },
              { value: ' '},
              { value: ' '},
              { value: ' '},
            ],
          },
          {
            data: [
              { value: 'CPL',
              styles: {
                fontWeight: 'bold',
                bgColor: '#D9EAD3',
              },
             },
              {
                value: `$${new Number(
                  computedReport?.value?.details?.am?.adwords?.cpl || 0
                ).toFixed(2)}`,
              },
              { value: ' '},
              { value: ' '},
              { value: ' '},
              { value: ' '},


              // Lead Source - FACEBOOK

              { value: 'CPL',
              styles: {
                fontWeight: 'bold',
                bgColor: '#C9DAF8',
              },
             },
              {
                value: `$${new Number(
                  computedReport?.value?.details?.am?.facebook?.cpl || 0
                ).toFixed(2)}`,
              },
              { value: ' '},
              { value: ' '},
              { value: ' '},
            ],
          },
          emptyLine,
          {
            data: [
              { value: 'Chat Summary',
              styles: {
                fontWeight: 'bold',
                bgColor: '#D9EAD3',
              },
            },
            { value: 'Count',
            styles: {
              fontWeight: 'bold',
              bgColor: '#D9EAD3',
            },
            },
            { value: 'Unique',
            styles: {
              fontWeight: 'bold',
              bgColor: '#D9EAD3',
            },
            },
            { value: 'Percentage of Unique Leads',
            styles: {
              fontWeight: 'bold',
              bgColor: '#D9EAD3',
            },
            },
            { value: ' X ',
            styles: {
              fontWeight: 'bold',
              bgColor: '#D9EAD3',
            },
            },
            { value: ' '},


              // Lead Source - FACEBOOK

            { value: 'Chat Summary',
            styles: {
              fontWeight: 'bold',
              bgColor: '#C9DAF8',
            },
            },
            { value: 'Count',
            styles: {
              fontWeight: 'bold',
              bgColor: '#C9DAF8',
            },
            },
            { value: 'Unique',
            styles: {
              fontWeight: 'bold',
              bgColor: '#C9DAF8',
            },
            },
            { value: 'Percentage of Unique Leads',
            styles: {
              fontWeight: 'bold',
              bgColor: '#C9DAF8',
            },
            },
            { value: ' X ', 
            styles: {
              fontWeight: 'bold',
              bgColor: '#C9DAF8',
            },
            },

            ],
          },
          {
            data: [
              { value: 'Chats started',
              styles: {
                bgColor: '#D9EAD3',
              },
             },
              { value: ' '},
              { value: ' '},
              { value: ' '},
              { value: ' '},
              { value: ' '},


              // Lead Source - FACEBOOK

              { value: 'Chats started',
              styles: {
                bgColor: '#C9DAF8',
              },
             },
              { value: ' '},
              { value: ' '},
              { value: ' '},
              { value: ' '},
            ],
          },
          {
            data: [
              { value: 'Chats converted to leads',
              styles: {
                bgColor: '#D9EAD3',
              },
            },
              { value: ' '},
              { value: ' '},
              { value: ' '},
              { value: ' '},
              { value: ' '},


              // Lead Source - FACEBOOK

              { value: 'Chats converted to leads',
              styles: {
                bgColor: '#C9DAF8',
              },
            },
              { value: ' '},
              { value: ' '},
              { value: ' '},
              { value: ' '},
            ],
          },
          {
            data: [
              { value: 'Leads as a % of Total Chats',
              styles: {
                fontWeight: 'bold',
                bgColor: '#D9EAD3',
              },
            },
              { value: 'Billable/Total Chats'},
              { value: ' '},
              { value: ' '},
              { value: ' '},
              { value: ' '},


              // Lead Source - FACEBOOK

              { value: 'Leads as a % of Total Chats',
              styles: {
                fontWeight: 'bold',
                bgColor: '#C9DAF8',
              },
            },
              { value: 'Billable/Total Chats'},
              { value: ' '},
              { value: ' '},
              { value: ' '},
            ],
          },
          emptyLine,

          {
            data: [
              { value: 'Calls Summary',
              styles: {
                fontWeight: 'bold',
                bgColor: '#D9EAD3',
              },
              },
              { value: 'Count',
              styles: {
                fontWeight: 'bold',
                bgColor: '#D9EAD3',
              },
              },
              { value: 'Unique',
              styles: {
                fontWeight: 'bold',
                bgColor: '#D9EAD3',
              },
              },
              { value: 'Percentage of Unique Leads',
              styles: {
                fontWeight: 'bold',
                bgColor: '#D9EAD3',
              },
              },
              { value: ' X ', 
              styles: {
                fontWeight: 'bold',
                bgColor: '#D9EAD3',
              },
              },
              { value: ' '},


              // Lead Source - FACEBOOK

              { value: 'Calls Summary',
              styles: {
                fontWeight: 'bold',
                bgColor: '#C9DAF8',
              },
              },
              { value: 'Count',
              styles: {
                fontWeight: 'bold',
                bgColor: '#C9DAF8',
              },
              },
              { value: 'Unique',
              styles: {
                fontWeight: 'bold',
                bgColor: '#C9DAF8',
              },
              },
              { value: 'Percentage of Unique Leads',
              styles: {
                fontWeight: 'bold',
                bgColor: '#C9DAF8',
              },
              },
              { value: ' X ', 
              styles: {
                fontWeight: 'bold',
                bgColor: '#C9DAF8',
              },
              },
            ],
          }, 
          {
            data: [
              { value: 'Appointments booked',
              styles: {
                bgColor: '#D9EAD3',
              },
            },
              { value: ' '},
              { value: computedReport.value.details.am.adwords.call_summary.booked || 0 },
              { value: ( computedReport.value.details.am.adwords.call_summary.booked / 
                ( computedReport.value.details.am.adwords.calls.unique ) ) == Infinity  ? 0 + '%' : 
                `${new Number(( computedReport.value.details.am.adwords.call_summary.booked / 
                ( computedReport.value.details.am.adwords.calls.unique ) ) || 0 * 100).toFixed(2)}%` },
              { value: ' '},
              { value: ' '},


              // Lead Source - FACEBOOK

              { value: 'Appointments booked',
              styles: {
                bgColor: '#C9DAF8',
              },
            },
              { value: ' '},
              { value: computedReport.value.details.am.facebook.call_summary.booked },
              { value:( computedReport.value.details.am.facebook.call_summary.booked / 
                ( computedReport.value.details.am.facebook.calls.unique ) ) == Infinity  ? 0 + '%' : 
                `${new Number(( computedReport.value.details.am.facebook.call_summary.booked / 
                ( computedReport.value.details.am.facebook.calls.unique ) ) || 0 * 100).toFixed(2)}%` },
              { value: ' '},
            ],
          },
          {
            data: [
              { value: 'Appointments NOT booked',
              styles: {
                bgColor: '#D9EAD3',
              },
            },
              { value: ' '},
              { value: computedReport.value.details.am.adwords.call_summary.not_booked },
              { value: ( computedReport.value.details.am.adwords.call_summary.not_booked / 
                ( computedReport.value.details.am.adwords.calls.unique ) ) == Infinity  ? 0 + '%' : 
                `${new Number(( computedReport.value.details.am.adwords.call_summary.not_booked / 
                ( computedReport.value.details.am.adwords.calls.unique ) ) || 0 * 100).toFixed(2)}%` },
              { value: ' '},
              { value: ' '},


              // Lead Source - FACEBOOK

              { value: 'Appointments NOT booked',
              styles: {
                bgColor: '#C9DAF8',
              },
            },
              { value: ' '},
              { value: computedReport.value.details.am.facebook.call_summary.not_booked },
              { value: ( computedReport.value.details.am.facebook.call_summary.not_booked / 
                ( computedReport.value.details.am.facebook.calls.unique ) ) == Infinity  ? 0 + '%' : 
                `${new Number(( computedReport.value.details.am.facebook.call_summary.not_booked / 
                ( computedReport.value.details.am.facebook.calls.unique ) ) || 0 * 100).toFixed(2)}%` },
              { value: ' '},
            ],
          }, 
          {
            data: [
              { value: 'Missed Calls',
              styles: {
                bgColor: '#D9EAD3',
              },
            },
              { value: ' '},
              { value: computedReport.value.details.am.adwords.call_summary.missed },
              { value: ( computedReport.value.details.am.adwords.call_summary.missed / 
                ( computedReport.value.details.am.adwords.calls.unique ) ) == Infinity  ? 0 + '%' : 
                `${new Number(( computedReport.value.details.am.adwords.call_summary.missed / 
                ( computedReport.value.details.am.adwords.calls.unique ) ) || 0 * 100).toFixed(2)}%` },
              { value: ' '},
              { value: ' '},


              // Lead Source - FACEBOOK

              { value: 'Missed Calls',
              styles: {
                bgColor: '#C9DAF8',
              },
            },
              { value: ' '},
              { value: computedReport.value.details.am.facebook.call_summary.missed  },
              { value: ( computedReport.value.details.am.facebook.call_summary.missed / 
                ( computedReport.value.details.am.facebook.calls.unique ) ) == Infinity  ? 0 + '%' : 
                `${new Number(( computedReport.value.details.am.facebook.call_summary.missed / 
                ( computedReport.value.details.am.facebook.calls.unique ) ) || 0 * 100).toFixed(2)}%` },
              { value: ' '},
            ],
          }, 
          {
            data: [
              { value: 'Irrelevant Calls',
              styles: {
                bgColor: '#D9EAD3',
              },
            },
              { value: ' '},
              { value: computedReport.value.details.am.adwords.call_summary.irrelevant  },
              { value: ( computedReport.value.details.am.adwords.call_summary.irrelevant / 
                ( computedReport.value.details.am.adwords.calls.unique ) ) == Infinity  ? 0 + '%' : 
                `${new Number(( computedReport.value.details.am.adwords.call_summary.irrelevant / 
                ( computedReport.value.details.am.adwords.calls.unique ) ) || 0 * 100).toFixed(2)}%` },
              { value: ' '},
              { value: ' '},


              // Lead Source - FACEBOOK
              { value: 'Irrelevant Calls',
              styles: {
                bgColor: '#C9DAF8',
              },
            },
              { value: ' '},
              { value: computedReport.value.details.am.facebook.call_summary.irrelevant },
              { value: ( computedReport.value.details.am.facebook.call_summary.irrelevant / 
                ( computedReport.value.details.am.facebook.calls.unique ) ) == Infinity  ? 0 + '%' : 
                `${new Number(( computedReport.value.details.am.facebook.call_summary.irrelevant / 
                ( computedReport.value.details.am.facebook.calls.unique ) ) || 0 * 100).toFixed(2)}%` },
              { value: ' '},

            ],
          }, 
          {
            data: [
              { value: 'Unscored Calls',
              styles: {
                bgColor: '#D9EAD3',
              },
            },
              { value: ' '},
              { value: computedReport.value.details.am.adwords.call_summary.unscored },
              { value: ( computedReport.value.details.am.adwords.call_summary.unscored / 
                ( computedReport.value.details.am.adwords.calls.unique ) ) == Infinity  ? 0 + '%' : 
                `${new Number(( computedReport.value.details.am.adwords.call_summary.unscored / 
                ( computedReport.value.details.am.adwords.calls.unique ) ) || 0 * 100).toFixed(2)}%` },
              { value: ' '},
              { value: ' '},


              // Lead Source - FACEBOOK

              { value: 'Unscored Calls',
              styles: {
                bgColor: '#C9DAF8',
              },
            },
              { value: ' '},
              { value: computedReport.value.details.am.facebook.call_summary.unscored },
              { value: ( computedReport.value.details.am.facebook.call_summary.unscored / 
                ( computedReport.value.details.am.facebook.calls.unique ) ) == Infinity  ? 0 + '%' :  
                `${new Number(( computedReport.value.details.am.facebook.call_summary.unscored / 
                ( computedReport.value.details.am.facebook.calls.unique ) ) || 0 * 100).toFixed(2)}%` },
              { value: ' '},
            ],
          },  
        ],
      },
      {
        title: 'All',
        headings: generateHeadersFromColumns(ldrAllColumns()),
        content: generateDataFromColumnsAndData({
          columns: ldrAllColumns(),
          data: computedReport?.value?.details?.all || [],
        }),
      },
      // {
      //   title: 'Calls',
      //   headings: generateHeadersFromColumns(ldrCallsColumns()),
      //   content: generateDataFromColumnsAndData({
      //     columns: ldrCallsColumns(),
      //     data: computedReport?.value?.details?.calls || [],
      //     rowStyle: (item: any) => {
      //       return {
      //         bgColor: item.rowColorHex,
      //       }
      //     },
      //   }),
      // },
      {
        title: 'CALLS-PPC',
        headings: generateHeadersFromColumns(ldr_PPC_CallsColumns()),
        content: generateDataFromColumnsAndData({
          columns: ldr_PPC_CallsColumns(),
          data: computedReport?.value?.details?.adwords_calls || [],
          rowStyle: (item: any) => {
            return {
              bgColor: item.rowColorHex,
            }
          },
        }),
      },
      {
        title: 'CALLS-FB',
        headings: generateHeadersFromColumns(ldr_FB_CallsColumns()),
        content: generateDataFromColumnsAndData({
          columns: ldr_FB_CallsColumns(),
          data: computedReport?.value?.details?.facebook_calls || [],
          rowStyle: (item: any) => {
            return {
              bgColor: item.rowColorHex,
            }
          },
        }),
      },
      {
        title: 'CALLS-SEO',
        headings: generateHeadersFromColumns(ldr_SEO_CallsColumns()),
        content: generateDataFromColumnsAndData({
          columns: ldr_SEO_CallsColumns(),
          data: computedReport?.value?.details?.seo_calls || [],
          rowStyle: (item: any) => {
            return {
              bgColor: item.rowColorHex,
            }
          },
        }),
      },
      // {
      //   title: 'Chats',
      //   headings: generateHeadersFromColumns(ldrChatsColumns()),
      //   content: generateDataFromColumnsAndData({
      //     columns: ldrChatsColumns(),
      //     data: computedReport?.value?.details?.chats || [],
      //     rowStyle: (item: any) => {
      //       var isWeekend = item.chat_date
      //         ? [0, 6].indexOf(new Date(item.chat_date).getDay()) != -1
      //         : false
      //       return {
      //         bgColor: isWeekend ? VuetifyColorsPallete['grey lighten-3'] : '',
      //       }
      //     },
      //   }),
      // },

      {
        title: 'CHATS-PPC',
        headings: generateHeadersFromColumns(ldr_PPC_ChatsColumns()),
        content: generateDataFromColumnsAndData({
          columns: ldr_PPC_ChatsColumns(),
          data: computedReport?.value?.details?.adwords_chats || [],
          rowStyle: (item: any) => {
            var isWeekend = item.chat_date
              ? [0, 6].indexOf(new Date(item.chat_date).getDay()) != -1
              : false
            return {
              bgColor: isWeekend ? VuetifyColorsPallete['grey lighten-3'] : '',
            }
          },
        }),
      },

      {
        title: 'CHATS-FB',
        headings: generateHeadersFromColumns(ldr_FB_ChatsColumns()),
        content: generateDataFromColumnsAndData({
          columns: ldr_FB_ChatsColumns(),
          data: computedReport?.value?.details?.facebook_chats || [],
          rowStyle: (item: any) => {
            var isWeekend = item.chat_date
              ? [0, 6].indexOf(new Date(item.chat_date).getDay()) != -1
              : false
            return {
              bgColor: isWeekend ? VuetifyColorsPallete['grey lighten-3'] : '',
            }
          },
        }),
      },

      {
        title: 'CHATS-SEO',
        headings: generateHeadersFromColumns(ldr_SEO_ChatsColumns()),
        content: generateDataFromColumnsAndData({
          columns: ldr_SEO_ChatsColumns(),
          data: computedReport?.value?.details?.seo_chats || [],
          rowStyle: (item: any) => {
            var isWeekend = item.chat_date
              ? [0, 6].indexOf(new Date(item.chat_date).getDay()) != -1
              : false
            return {
              bgColor: isWeekend ? VuetifyColorsPallete['grey lighten-3'] : '',
            }
          },
        }),
      },

      {
        title: 'FORMS-PPC',
        headings: generateHeadersFromColumns(ldr_PPC_FormsColumns()),
        content: generateDataFromColumnsAndData({
          columns: ldr_PPC_FormsColumns(),
          data: computedReport?.value?.details?.emails || [],
          rowStyle: (item: any) => {
            var isWeekend = item.created
              ? [0, 6].indexOf(new Date(item.created).getDay()) != -1
              : false
            return {
              bgColor: isWeekend ? VuetifyColorsPallete['grey lighten-3'] : '',
            }
          },
        }),
      },

      {
        title: 'FORMS-FB',
        headings: generateHeadersFromColumns(ldr_FB_FormsColumns()),
        content: generateDataFromColumnsAndData({
          columns: ldr_FB_FormsColumns(),
          data: computedReport?.value?.details?.facebook_leads || [],
        }),
      },

      {
        title: 'FORMS-SEO',
        headings: generateHeadersFromColumns(ldr_SEO_FormsColumns()),
        content: generateDataFromColumnsAndData({
          columns: ldr_SEO_FormsColumns(),
          data: computedReport?.value?.details?.seo_emails || [],
        }),
      },
    ],
  }
}

export default generateLeadDetailsReport
